apiVersion: wso2.wso2.com/v1beta1
kind: Userstore
metadata:
  name: userstore5
auth:
  host: identityserver
  username: admin
  password: admin
spec:
  typeId: VW5pcXVlSURKREJDVXNlclN0b3JlTWFuYWdlcg
  description: Secondary userstore for identity server
  name: wso2.com
  properties:
    - name: url
      value: jdbc:mysql://192.168.99.1:3306/IS_USER_STORE?autoReconnect=true&amp;useSSL=false
    - name: userName
      value: root
    - name: password
      value: '1234'
    - name: driverName
      value: com.mysql.jdbc.Driver